server:
  port: 10003

eureka:
  instance:
    hostname: eureka10003.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka10001.com:10001/eureka,http://eureka10002.com:10002/eureka