server:
  port: 11001
spring:
  application:
    name: service-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3309/springcloud-order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Root123;
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mybatis/mapper/*-mapper.xml
  type-aliases-package: com.xywei.domain

# Eureka配置
eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true # 需要把自己注册到Eureka服务器
    fetch-registry: true #需要抓取已有的注册信息
    service-url:
      defaultZone: http://eureka10001.com:10001/eureka,http://eureka10002.com:10002/eureka,http://eureka10003.com:10003/eureka
# version没有作用
info:
  app.name: ${spring.application.name}
  build.artifactId: $project.artifactId$
  build.version: $project.version$