server:
  port: 10002

eureka:
  instance:
    hostname: eureka10002.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka10001.com:10001/eureka, http://eureka10003.com:10003/eureka
